name: Hello Workflow
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Print Hello
      - uses: echo "Hello GitHub Actions"
      
      - name: Show Current Date
        run: date
  
